FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
COPY index.html ./
COPY tsconfig*.json ./
COPY env.d.ts ./
COPY vite.config.ts ./
COPY public ./public
COPY front-end ./front-end

ARG VITE_API_BASE_URL=http://localhost:3000
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN npm ci
RUN npm run build

FROM nginx:1.27-alpine AS runtime
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
